name: midway-fc-deploy-action

description: Midway Serverless Deploy Action For Aliyun FC

inputs:
  id: 
    description: 'FC Account ID'
    required: true
  ak: 
    description: 'FC Account Access Key'
    required: true
  secret: 
    description: 'FC Account Access Secret'
    required: true
  endpoint: 
    description: 'FC Endpoint'
    default: 'cn-hangzhou'
  timeout: 
    description: 'Deploy Timeout'
    default: '1000'

    
runs:
  using: 'node12'
  main: 'index.js'